name: Gamble
version: ${project.version}
authors: [ DR_Division, LemonCaramel ]
main: com.division.Gamble
depend: [ caramelCounterZombieLegacy, Vault ]
api-version: 1.15
commands:
  gamble:
    aliases: [ 도박 ]
    description: about Gamble